In [1]:
from array import array

w numpy mamy obiekt: 'array (ndarray)


In [2]:
!pip install numpy

You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
###b = np.array([0,1,2,3][1,2,3,4,5]]]) - można inaczej

In [5]:
b = np.arange(15)
b = b.reshape(3, 5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
b.ndim

2

In [8]:
b.shape

(3, 5)

In [9]:
b.dtype.name

'int32'

In [11]:
2**32

4294967296

In [13]:
b.itemsize

4

In [15]:
b.size

15

In [16]:
## tworzenie tablic ##

In [17]:
c = np.array([1.1, 2.2, 3.3])

In [18]:
c.dtype

dtype('float64')

In [19]:
np.array([1, 2.2, 3])

array([1. , 2.2, 3. ])

In [20]:
np.array([1, 2, 3], dtype=np.float32)

array([1., 2., 3.], dtype=float32)

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros(10,1)

TypeError: data type not understood

In [25]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

np.eye(10)

In [30]:
np.arange(8).reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [33]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [35]:
np.linspace(0, 9, 20)

array([0.        , 0.47368421, 0.94736842, 1.42105263, 1.89473684,
       2.36842105, 2.84210526, 3.31578947, 3.78947368, 4.26315789,
       4.73684211, 5.21052632, 5.68421053, 6.15789474, 6.63157895,
       7.10526316, 7.57894737, 8.05263158, 8.52631579, 9.        ])

In [36]:
print(np.arange(8).reshape((4, 2)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [37]:
np.arange(8).reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [43]:
a = np.arange(8).reshape((4, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [39]:
a * 5

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35]])

In [44]:
b = a * 5
b

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35]])

In [45]:
a-b

array([[  0,  -4],
       [ -8, -12],
       [-16, -20],
       [-24, -28]])

In [46]:
b-a

array([[ 0,  4],
       [ 8, 12],
       [16, 20],
       [24, 28]])

In [47]:
a/b

c:\users\kurs\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 0.2],
       [0.2, 0.2],
       [0.2, 0.2],
       [0.2, 0.2]])

In [48]:
a*b

array([[  0,   5],
       [ 20,  45],
       [ 80, 125],
       [180, 245]])

In [49]:
a**b

array([[         1,          1],
       [      1024,   14348907],
       [         0,  167814181],
       [1073741824,  613813847]], dtype=int32)

In [ ]:
A = np.array([[1,1],
             [0,1]])
B = 

A.dot(B)


In [54]:
b

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35]])

In [53]:
b[2][1]

25

In [55]:
b

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35]])